apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: geaazf38f-python
  janus-idp.io/tekton: geaazf38f-python
  backstage.io/kubernetes-id: geaazf38f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: geaazf38f-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
